name: notes_app
description: A Flutter app to create notes with tags.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  bloc: ^8.1.1
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.2.0
  go_router: ^6.5.3
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
